Repository openauth-dev/SocialiteOpenAuthProvider, pull requests merged in 2020-07, with the labels that each got.

#7 fix: package-ecosystem
  .github/dependabot.yml
Labels: bug

#8 Update README.md
  README.md
Labels: bug, documentation

#9 Update README
  .github/dependabot.yml
  README.md
Labels: documentation

#10 Update README (#9)
  README.md
Labels: documentation

#13 feat: merge next to master
  Provider.php
  README.md
Labels: documentation, enhancement

#15 Update build.yml
  .github/workflows/build.yml
Labels: bug

#20 feat: Add templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation, enhancement

#14 feat: Add homepage and role of authors
  composer.json
Labels: documentation

#22 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement
